// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace School.Entities
{
    public partial class getDepartmentCoursesResult
    {
        public string Col0 { get; set; }
    }
}
